CREATE TABLE `auth_tokens` (
  `token` VARCHAR(128) PRIMARY KEY,
  `is_admin_token` TINYINT(1) NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE `users` (
  `uid` SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  `username` VARCHAR(32) UNIQUE NOT NULL,
  `password_hash` BINARY(60) NOT NULL,
  `name` VARCHAR(16) NOT NULL,
  `is_admin` TINYINT(1) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE `categories` (
  `name` VARCHAR(16) PRIMARY KEY,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE `articles` (
  `uid` SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  `uploader_uid` SMALLINT UNSIGNED,
  `category_name` VARCHAR(16),
  `thumbnail_name` VARCHAR(255) NOT NULL,
  `thumbnail_caption` VARCHAR(256) NOT NULL,
  `title` VARCHAR(256) NOT NULL,
  `subtitle` VARCHAR(512) NOT NULL,
  `content` TEXT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `fk_uploader_uid` FOREIGN KEY (`uploader_uid`) REFERENCES `users`(`uid`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_category_name` FOREIGN KEY (`category_name`) REFERENCES `categories`(`name`) ON DELETE SET NULL ON UPDATE CASCADE
);
