CREATE DATABASE IF NOT EXISTS NEWS DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;
USE NEWS;
CREATE TABLE USER(
    `UID` UNSIGNED SMALLINT AUTO_INCREMENT PRIMARY KEY,
    `EMAIL` VARCHAR(320) NOT NULL,
    `PASSWORD_HASH` BINARY(60) NOT NULL,
    `NAME` VARCHAR(32) NOT NULL,
    `AUTH_TOKEN` VARCHAR(64) NOT NULL,
    `AUTH_TOKEN_ISSUE_DATE` TIMESTAMP NOT NULL,
)
CREATE TABLE AUTH_TOKEN(
    `TOKEN` VARCHAR(64) NOT NULL,
    `ISSUE_DATE` TIMESTAMP NOT NULL,
    `EXPIRATION_PERIOD` TIMESTAMP NOT NULL,
)