CREATE DATABASE IF NOT EXISTS `NEWS` DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;
USE `NEWS`;
CREATE TABLE `USER`(
    `UID` UNSIGNED SMALLINT AUTO_INCREMENT PRIMARY KEY,
    `UUID` BINARY(16) NOT NULL UNIQUE,
    `EMAIL` VARCHAR(320) NOT NULL,
    `PASSWORD_HASH` BINARY(60) NOT NULL,
    `NAME` VARCHAR(32) NOT NULL,
    `CREATION_DATE` TIMESTAMP NOT NULL,
    `AUTH_TOKEN` FOREIGN KEY REFERENCES `AUTH_TOKEN`(`UID`),
)
CREATE TABLE `AUTH_TOKEN`(
    `UID` FOREIGN KEY REFERENCES `USER`(`UID`),
    `TOKEN` VARCHAR(64) NOT NULL,
    `ISSUE_DATE` TIMESTAMP NOT NULL,
    `EXPIRATION_PERIOD` TIMESTAMP NOT NULL,
    `USED` BOOLEAN NOT NULL,
    `ADMIN` BOOLEAN NOT NULL,
)